tactician:
  commandbus:
    default:
      middleware:
        - tactician.middleware.locking
        - Ticket\Infrastructure\Middleware\CommandBus\DoctrineTransactionMiddleware
        - tactician.middleware.command_handler