createCategory:
    path: /api/category
    methods: POST
    controller: Ticket\Infrastructure\Delivery\Api\Controller\CategoryController::createCategory

getCategory:
    path: /api/category
    methods: GET
    controller: Ticket\Infrastructure\Delivery\Api\Controller\CategoryController::getCategories

editCategory:
    path: /api/category/{categoryId}
    methods: PUT
    controller: Ticket\Infrastructure\Delivery\Api\Controller\CategoryController::editCategory

removeCategory:
    path: /api/category/{categoryId}
    methods: DELETE
    controller: Ticket\Infrastructure\Delivery\Api\Controller\CategoryController::removeCategory

createTicket:
    path: /api/ticket
    methods: POST
    controller: Ticket\Infrastructure\Delivery\Api\Controller\TicketController::createTicket

editTicket:
    path: /api/ticket/{ticketId}
    methods: PUT
    controller: Ticket\Infrastructure\Delivery\Api\Controller\TicketController::editTicket

resolveTicket:
    path: /api/ticket/{ticketId}/resolve
    methods: PATCH
    controller: Ticket\Infrastructure\Delivery\Api\Controller\TicketController::resolveTicket

addComment:
    path: /api/comment
    methods: POST
    controller: Ticket\Infrastructure\Delivery\Api\Controller\CommentController::addComment

editComment:
    path: /api/comment/{commentId}
    methods: PUT
    controller: Ticket\Infrastructure\Delivery\Api\Controller\CommentController::editComment

removeComment:
    path: /api/comment/{commentId}
    methods: DELETE
    controller: Ticket\Infrastructure\Delivery\Api\Controller\CommentController::removeComment
